language: node_js
node_js:
  - lts/*
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE courses;" -U postgres
  - psql -c "CREATE USER coursesuser WITH PASSWORD '1';" -U postgres
  - 'npm run build:db'
env:
  global:
    - PGPORT=5432
test:
  adapter: postgresql
  database: courses
