const categoryId = {
  'Empire: the Controversies of British Imperialism': 15,
  'COVID-19: Psychological First Aid': 13,
  'Data Analytics for Decision Making: An Introduction to Using Excel': 6,
  'Becoming a Teacher': 15,
  'Addressing Postnatal Depression as a Healthcare Professional': 13,
  'Antimicrobial Stewardship for Africa': 13,
  'Bullying in Schools: How Should Teachers Respond?': 15,
  'COVID-19: Diagnostics and Testing': 13,
  'Earn a degree from a leading university': 15,
  'COVID-19: Psychological First Aid': 13,
  'Coaching in Education: Addressing the Need for Deep Communication': 7,
  'Creating Apps in the Classroom': 2,
  'Develop Your Cultural Intelligence': 7,
  'Digital Media Analytics: Using Data from Owned Media': 6,
  'Digital Product Management': 6,
  'Digital Transformation in the Classroom': 15,
  'Discover Dentistry': 13,
  'Discovering Your PhD Potential: Writing a Research Proposal': 15,
  'Entrepreneurship: From Business Idea to Action': 5,
  'Farm to Fork: Sustainable Food Production in a Changing Environment': 9,
  'Good Brain, Bad Brain: Drug Origins': 13,
};

module.exports = categoryId;
